import type { Config } from "@react-router/dev/config";

export default {
  prerender: async () => {
    return [
      "/",
      "/about",
      "/choose-a-personality",
      "/default-roundedness",
      "/getting-started",
      "/rest-parameters",
      "/components/data-display/badge",
      "/components/data-display/card",
      "/components/data-display/table",
      "/components/feedback/alert",
      "/components/feedback/progress",
      "/components/form/button",
      "/components/form/checkbox-card-group",
      "/components/form/checkbox",
      "/components/form/form-field",
      "/components/form/input",
      "/components/form/password-input",
      "/components/form/radio-button-card-group",
      "/components/form/radio-button-group",
      "/components/form/radio-button",
      "/components/form/select",
      "/components/form/stepper",
      "/components/form/switch",
      "/components/form/textarea",
      "/components/layout/container",
      "/components/layout/flex",
      "/components/layout/stack",
      "/components/navigation/breadcrumbs",
      "/components/navigation/footer",
      "/components/navigation/link",
      "/components/navigation/navbar",
      "/components/navigation/navigation-links",
      "/components/navigation/tabs",
      "/components/navigation/vertical-navbar",
      "/components/overlays/help-tooltip",
      "/components/overlays/info-tooltip",
      "/components/overlays/modal",
      "/components/overlays/popover",
      "/components/overlays/tooltip",
      "/components/typography/blockquote",
      "/components/typography/code-block",
      "/components/typography/h1",
      "/components/typography/h2",
      "/components/typography/highlight",
      "/components/typography/inline-code",
      "/components/typography/ol",
      "/components/typography/text",
      "/components/typography/ul",
    ];
  },
} satisfies Config;
